### ISSUE TITLE
RabbitMQ channel leaking

### ISSUE THREAD

**Issue by wangjia184** [KevinCathcart/Orleans.Streams.RabbitMqStreamProvider#5]
After using this provider on production, we encounter `ChannelAllocationException` when the provider was trying to create new channel.

```
RabbitMqException : RabbitMqProducer: Send failed! [The connection cannot support any more channels. Consider creating a new connection]
   at RabbitMQ.Client.Impl.SessionManager.Create()
   at RabbitMQ.Client.Framing.Impl.Connection.CreateModel()
   at Orleans.Streams.RabbitMq.RabbitMqConnector.EnsureChannelAvailable() in /app/Orleans.Streams.RabbitMqStreamProvider/Orleans.Streams.RabbitMqStreamProvider/RabbitMq/RabbitMqConnector.cs:line 60
   at Orleans.Streams.RabbitMq.RabbitMqConnector.get_Channel() in /app/Orleans.Streams.RabbitMqStreamProvider/Orleans.Streams.RabbitMqStreamProvider/RabbitMq/RabbitMqConnector.cs:line 35
   at Orleans.Streams.RabbitMq.RabbitMqProducer.SendImpl(RabbitMqMessage message) in /app/Orleans.Streams.RabbitMqStreamProvider/Orleans.Streams.RabbitMqStreamProvider/RabbitMq/RabbitMqProducer.cs:line 112
━━━━━━━━━━━━
```

The reason is that -- `RabbitMqConnector` is created per each thread using `ThreadLocal`
Somehow the created `RabbitMqConnector` instance does not recycle and the number of instances keeps increasing. Till it hits the `channel_max` limitation of RabbitMQ and exhausted all channels and `ChannelAllocationException` is raised.

A PR is raised: https://github.com/KevinCathcart/Orleans.Streams.RabbitMqStreamProvider/pull/6

**Comment by keithn** [comment]
are you still using this @wangjia184 ?  and do you know if it works with the latest .net 7 version?  the project seems a bit dead

**Comment by wangjia184** [comment]
I dont use it any mmore @keithn
